# Generated by Django 3.2.6 on 2023-05-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['slug']},
        ),
    ]
